version: '2.1'

services:
  moonapp:
    build: .
    ports:
      - 8080:8080
    depends_on:
      moonredis:
        condition: service_healthy

  moonredis:
    image: redis:5.0.5-alpine
    container_name: moon_redis
    command: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 3
#    ports:
#      - 6379:6379